# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsgames-admin
  labels:
    app: lsgames-admin
  namespace: smkz-for-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsgames-admin
  template:
    metadata:
      labels:
        app: lsgames-admin
    spec:
      volumes:
        # 若有需要將 configs.json 綁定到容器中，請打開以下註解
        # 請務必先建立 <CONFIG_MAP_NAME> 的 configMap 否則部署會失敗
        - name: config-volume
          configMap:
            name: lsgames-admin-configs
      containers:
        - name: lsgames-admin
          image: $secrets.REGISTRY_URL/lsgames-admin:latest
          # 若有需要將 configs.json 綁定到容器中，請打開以下註解
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/configs.json
              subPath: config.json
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 80
              protocol: TCP

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lsgames-admin
  namespace: smkz-for-work
spec:
  type: ClusterIP
  selector:
    app: lsgames-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
